### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nk932714** [ahadyekta/youtube-link-extractor#1]
when in demo i entered the values and click on submit nothing happens

**Comment by ahadyekta** [comment]
What is the value you entered? Maybe there is no channel name or user id with that value or you don`t have access to it

**Comment by nk932714** [comment]
i have entered the Google API key **************_*
then youtube channel id, user id, playlist
Can you please test at your end is it working or not ?

**Comment by nk932714** [comment]
thanks its working  i was entering all these values " channel id, user id, playlist"
👍
