### ISSUE TITLE
Empty result for valid Playlist Id and API key

### ISSUE THREAD

**Issue by motsmanish** [ahadyekta/youtube-link-extractor#2]
Received following response:
`{
 "kind": "youtube#channelListResponse",
 "etag": "\"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\"",
 "pageInfo": {
  "totalResults": 0,
  "resultsPerPage": 50
 },
 "items": []
}`

**Comment by ahadyekta** [comment]
What is your input . You may misspell the channel name

**Comment by motsmanish** [comment]
Thanks for following up on the issue.
Here is the playlist:
https://www.youtube.com/playlist?list=PLwpFrtWg2EJHyqlGm8qNueXjFRvSXu8Ft
My API key is valid because I have used it in my applications for GMAIL and
DRIVE.

Thanks & Regards,
Manish Motwani
*http://ManishMotwani.com <http://manishmotwani.com/>*

**Comment by ahadyekta** [comment]
You can get the playlist by its channel Id 
UCUZDJBrgyWmcD9gLP4kl53w

https://www.youtube.com/channel/UCUZDJBrgyWmcD9gLP4kl53w
after loading channel , playlists will appear

**Comment by motsmanish** [comment]
Okay. It works with channel ID, I thought it works with playlist ID (PLwpFrtWg2EJHyqlGm8qNueXjFRvSXu8Ft) as well.

**Comment by motsmanish** [comment]
When I tried your channel id, it gave me thumbnails and list at the bottom.
For my channel id, it only gave thumbnails (UCsT0YIqwnpJCM-mx7-gSA4Q), can you please guide me.

**Comment by motsmanish** [comment]
Thanks.
